version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  test:
    build: .
    volumes:
      - .:/app
    command: ["pytest"]


  # ngrok:
  #   image: wernight/ngrok
  #   environment:
  #     - NGROK_PORT=app:8000  # Faz o ngrok se conectar ao serviço app na porta 8000
  #     - NGROK_AUTH=2Ge1pMqVlAtPyTjvvdXLlGIsLg4_5BHmZV91sehFaNYeLwG7u  # Substitua pelo seu token de autenticação do ngrok (opcional)
  #   ports:
  #     - "4040:4040"  # Porta para acessar o dashboard do ngrok
  #   depends_on:
  #     - app  # Certifique-se de que o app suba antes do ngrok
