version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"  # Mapeia a porta 8000 do host para a porta 8000 do container
    volumes:
      - .:/app  # Monta o diretório atual no diretório de trabalho do container para recarregar automaticamente as alterações
    env_file:
      - .env  # Carrega as variáveis de ambiente do arquivo .env




  # ngrok:
  #   image: wernight/ngrok
  #   environment:
  #     - NGROK_PORT=app:8000  # Faz o ngrok se conectar ao serviço app na porta 8000
  #     - NGROK_AUTH=2Ge1pMqVlAtPyTjvvdXLlGIsLg4_5BHmZV91sehFaNYeLwG7u  # Substitua pelo seu token de autenticação do ngrok (opcional)
  #   ports:
  #     - "4040:4040"  # Porta para acessar o dashboard do ngrok
  #   depends_on:
  #     - app  # Certifique-se de que o app suba antes do ngrok
